### ISSUE TITLE
Crash when dispatching event on TCP

### ISSUE THREAD

**Issue by HornWilly** [Tropicao/zigbridge#10]
INF<29558>:zg_interfaces ../src/interfaces/interfaces.c:242 zg_interfaces_send_event() Sending event new_device to remote clients
DBG<29558>:zg_interfaces ../src/interfaces/interfaces.c:282 zg_interfaces_send_event() [TCP] Dispatch event
Segmentation fault (core dumped)

**Comment by Tropicao** [comment]
Fixed by https://github.com/Tropicao/zigbridge/commit/93d671f2ddac871ad0fefcdff4391567d975bbb8
