### ISSUE TITLE
Crash on save device list

### ISSUE THREAD

**Issue by HornWilly** [Tropicao/zigbridge#9]
INF<29527>:zg_devices ../src/devices/device.c:503 zg_add_device() Saving new device with id 0
INF<29527>:zg_devices ../src/devices/device.c:425 _save_device_list() Stored data for device 0xC5B2
ERR<29527>:zg_devices ../src/devices/device.c:431 _save_device_list() Cannot save device list in file /etc/zigbridge/devices.json

I think it's because the directory dosen't exist.

**Comment by Tropicao** [comment]
Fixed by https://github.com/Tropicao/zigbridge/commit/7ef57c1c5c1a98fbf6cea693a71c267404c34bea
